### ISSUE TITLE
Detect Elgg deprecated function usage

### ISSUE THREAD

**Issue by cash** [Elgg/elgg-coding-standards#8]
get_defined_functions() will come in handy for this. Also something using this:

```
$rf = new ReflectionFunction('extend_view');
var_dump(strpos($rf->getFileName(), "engine/lib/deprecated"));
var_dump(strpos($rf->getDocComment(), "@deprecated"));
```

Take a look at https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/PHP/DeprecatedFunctionsSniff.php

**Comment by jdalsem** [comment]
not going to use this atm
